[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wiki_modular"
version = "0.1.0"
dependencies = [
    "pyyaml>=6.0"
]

[tool.setuptools]
py-modules = []

