name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Python versions must be quoted so YAML does not treat them as floats
        python-version: ['3.10', '3.11', '3.12']
    steps:
      # Descarga el código
      - uses: actions/checkout@v3

      # Cache de dependencias pip
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Configura Python
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Instalación de dependencias y herramientas de testing
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest pytest-cov pre-commit

      # Ejecuta validaciones de pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color always

      # Ejecuta tests con cobertura
      - name: Run tests with coverage
        run: pytest --cov=.

      # (Opcional) Sube reporte de cobertura a Codecov o Coveralls
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage.xml
      #     flags: unittests
      #     name: codecov-umbrella
